module.exports = {
    BILL_EXISTS: "BILL_EXISTS",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    BILL_NOT_PAID: "BILL_NOT_PAID",
    PAYMENT_CODE_NOT_FOUND: "PAYMENT_CODE_NOT_FOUND",
    NO_BILL_FOUND: "NO_BILL_FOUND",
    SOMETHING_IS_WRONG: "SOMETHING_IS_WRONG",
    CLAIMED:"CLAIMED",
    USER_ID_NOT_FOUND:"USER_ID_NOT_FOUND"
};